name: "units-test"
on:
  pull_request_target:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        milliseconds: 1000

        on: pull_request_target

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to comment hello
    steps:
    - name: Hello world action step
      id: hello
      uses: HarishTeens/woofy@master
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

