on: pull_request_target
jobs:  
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to comment hello
    steps:
    - name: Hello world action step
      id: hello
      uses: HarishTeens/javascript-action-temp@v1.0.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}