name: "units-test"
on:
  pull_request_target:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to comment hello
    steps:
    - name: Hello world action step
      id: hello
      uses: HarishTeens/javascript-action-temp@test
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

